[build]
  publish = "dist"
  command = "yarn build"

[context.production]
  [context.production.environment]
    APP_BASE_URL='https://jonblackjack.netlify.com'
    APP_ENV="production"
    FACEBOOK_APP_ID="205877129893516"
    GA_PROPERTY="UA-92969366-1"
    NODE_ENV="production"
    YARN_FLAGS="--production=false"
    YARN_VERSION="1.9.4"
